### ISSUE TITLE
AttributeError: 'array.array' object has no attribute 'fromstring' during flash

### ISSUE THREAD

**Issue by raccoondude** [numworks/epsilon#1742]
Currently when flashing, an error is thrown, this happens during compiling

The error is

```Makefile:29: HOME_DISPLAY_EXTERNALS is set but external isn't included, ignoring flag.
DFU     epsilon_flash
INFO    About to flash your device. Please plug your device to your computer
        using an USB cable and press the RESET button the back of your device.
Mass erase...
Traceback (most recent call last):
  File "/home/owo/Omega/build/device/usb/core.py", line 1023, in ctrl_transfer
    buff = util.create_buffer(data_or_wLength)
  File "/home/owo/Omega/build/device/usb/util.py", line 149, in create_buffer
    return array.array('B', _dummy_s * length)
TypeError: can't multiply sequence by non-int of type 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/owo/Omega/build/device/usb/_interop.py", line 79, in as_array
    return array.array('B', data)
TypeError: cannot use a str to initialize an array with typecode 'B'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/owo/Omega/build/device/dfu.py", line 598, in <module>
    main()
  File "/home/owo/Omega/build/device/dfu.py", line 582, in main
    mass_erase()
  File "/home/owo/Omega/build/device/dfu.py", line 163, in mass_erase
    __dev.ctrl_transfer(0x21, __DFU_DNLOAD, 0, __DFU_INTERFACE,
  File "/home/owo/Omega/build/device/usb/core.py", line 1025, in ctrl_transfer
    buff = _interop.as_array(data_or_wLength)
  File "/home/owo/Omega/build/device/usb/_interop.py", line 84, in as_array
    a.fromstring(data) # deprecated since 3.2
AttributeError: 'array.array' object has no attribute 'fromstring'
make: *** [build/targets.device.n0100.mak:7: epsilon_flash] Error ```

Im using Python 3.9.1

Im very confused as to why this is happening :/

**Comment by cybfr** [comment]
Had the same error :+1: 
```
xx@xxx:~/ws/numworks/epsilon$ make MODEL=n0100 epsilon_flash
DFU     epsilon_flash
INFO    About to flash your device. Please plug your device to your computer
        using an USB cable and press the RESET button the back of your device.
Mass erase...
Traceback (most recent call last):
  File "/home/xxx/ws/numworks/epsilon/build/device/usb/core.py", line 1023, in ctrl_transfer
    buff = util.create_buffer(data_or_wLength)
  File "/home/xxx/ws/numworks/epsilon/build/device/usb/util.py", line 149, in create_buffer
    return array.array('B', _dummy_s * length)
TypeError: can't multiply sequence by non-int of type 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxxx/ws/numworks/epsilon/build/device/usb/_interop.py", line 79, in as_array
    return array.array('B', data)
TypeError: cannot use a str to initialize an array with typecode 'B'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxx/ws/numworks/epsilon/build/device/dfu.py", line 598, in <module>
    main()
  File "/home/xxx/ws/numworks/epsilon/build/device/dfu.py", line 582, in main
    mass_erase()
  File "/home/xxx/ws/numworks/epsilon/build/device/dfu.py", line 163, in mass_erase
    __dev.ctrl_transfer(0x21, __DFU_DNLOAD, 0, __DFU_INTERFACE,
  File "/home/xx/ws/numworks/epsilon/build/device/usb/core.py", line 1025, in ctrl_transfer
    buff = _interop.as_array(data_or_wLength)
  File "/home/xxx/ws/numworks/epsilon/build/device/usb/_interop.py", line 84, in as_array
    a.fromstring(data) # deprecated since 3.2
AttributeError: 'array.array' object has no attribute 'fromstring'
make: *** [build/targets.device.n0100.mak:7 : epsilon_flash] Erreur 1
```

Python version :+1: 
$ python -V
Python 2.7.18

Using #1743 fixed it

**Comment by TheBonnec** [comment]
I had the same error. I tried with multiple versions of Epsilon (15 and 13) and Omega (1.21) but nothing changed, the same error message appeared...

PS : I'm on a 2011 MacBook Air with macOS Catalina

`make MODEL=n0100 epsilon_flash
DFU     epsilon_flash
INFO    About to flash your device. Please plug your device to your computer
        using an USB cable and press the RESET button the back of your device.
Mass erase...
Traceback (most recent call last):
  File "/Users/thomaslebonnec/epsilon-13/build/device/usb/core.py", line 1023, in ctrl_transfer
    buff = util.create_buffer(data_or_wLength)
  File "/Users/thomaslebonnec/epsilon-13/build/device/usb/util.py", line 149, in create_buffer
    return array.array('B', _dummy_s * length)
TypeError: can't multiply sequence by non-int of type 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thomaslebonnec/epsilon-13/build/device/usb/_interop.py", line 79, in as_array
    return array.array('B', data)
TypeError: cannot use a str to initialize an array with typecode 'B'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thomaslebonnec/epsilon-13/build/device/dfu.py", line 598, in <module>
    main()
  File "/Users/thomaslebonnec/epsilon-13/build/device/dfu.py", line 582, in main
    mass_erase()
  File "/Users/thomaslebonnec/epsilon-13/build/device/dfu.py", line 163, in mass_erase
    __dev.ctrl_transfer(0x21, __DFU_DNLOAD, 0, __DFU_INTERFACE,
  File "/Users/thomaslebonnec/epsilon-13/build/device/usb/core.py", line 1025, in ctrl_transfer
    buff = _interop.as_array(data_or_wLength)
  File "/Users/thomaslebonnec/epsilon-13/build/device/usb/_interop.py", line 84, in as_array
    a.fromstring(data) # deprecated since 3.2
AttributeError: 'array.array' object has no attribute 'fromstring'
make: *** [epsilon_flash] Error 1`
