### ISSUE TITLE
epsilon-build-related python script issue: python 3.6

### ISSUE THREAD

**Issue by yeKcim** [numworks/epsilon#203]
Can't compile with python 3.6. First, there is the sets  #197, but if I correct this bug, there is these : 

$ make
```
…
I18N    apps/i18n.cpp
Traceback (most recent call last):
  File "apps/i18n.py", line 167, in <module>
    data = parse_files(args.files)
  File "apps/i18n.py", line 55, in parse_files
    name,definition = split_line(line)
  File "apps/i18n.py", line 40, in split_line
    return (match.group(1), source_definition(match.group(2)))
  File "apps/i18n.py", line 31, in source_definition
    ion_characters.append(ion_char(i18n_letter))
  File "apps/i18n.py", line 26, in ion_char
    return "'" + normalized + "'"
TypeError: must be str, not bytes
make: *** [apps/Makefile:81: apps/i18n.cpp] Error 1
```

$ python --version
```
Python 3.6.2
```

Seems to be little bug, it could be interesting to be 3.6 compliant…

**Comment by ian-abbott** [comment]
I don't think it works with any version of Python 3. The easiest fix is to run python2 explicitly, but that assumes the system adheres to [PEP 394](https://www.python.org/dev/peps/pep-0394/).

**Comment by yeKcim** [comment]
add 2 at the end of the first line `#!/usr/bin/python2` in apps/i18n.cpp is not efficient

**Comment by ian-abbott** [comment]
@yeKcim I think you mean apps/i18n.py and "sufficient". The script is not executed directly via the magic "shebang" line (`#!`). It is run as an argument of the python command from apps/Makefile. So apps/Makefile needs a small change to run python2 instead of python.

**Comment by yeKcim** [comment]
I tried
```
export PYTHON=python2.7
make
```

Still have errors.

Thank you for correcting my English @ian-abbott (and file name).

**Comment by adriweb** [comment]
Well sure, it's just calling `python` directly, not an env var. https://github.com/numworks/epsilon/blob/e6ed6c7/apps/Makefile#L81

**Comment by yeKcim** [comment]
the only solution I found: https://wiki.archlinux.org/index.php/Python#Python_2

Add a /usr/local/bin/python file:
```
#!/bin/bash
script=$(readlink -f -- "$1")
case "$script" in (~/epsilon/*)
    exec python2 "$@"
    ;;
esac

exec python3 "$@"
```
(change `~/epsilon/` with your git dir)

With this file, manjaro or archlinux can compile epsilon

**Comment by adriweb** [comment]
Or, you know, just force `python2` in the Makefile and add a note in the readme :P

**Comment by yeKcim** [comment]
I've tried but just write python2 instead of python in the makefile didn't work, if this had worked I would have proposed the modification via a git push. I know nothing about makefiles.

**Comment by demastrie** [comment]
I changed `@python` to ` @python2` on line 68 of apps/Makefile and my build completed.
